
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x0f\x87\xb1\x96\xf5\xfa\xf7\xdbI\x1e\x14\x1d\xd2T\xab\x82'
    
_lr_action_items = {'CTAG':([4,5,6,7,8,9,10,11,12,13,14,15,],[6,9,-1,12,13,-4,14,15,-3,-2,-6,-5,]),'OTAG':([0,4,5,],[2,2,2,]),'CONTENT':([4,5,],[8,11,]),'$end':([1,6,9,12,13,14,15,],[0,-1,-4,-3,-2,-6,-5,]),'CLASS':([2,],[3,]),'>':([2,3,],[4,5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'obj':([0,4,5,],[1,7,10,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> obj","S'",1,None,None,None),
  ('obj -> OTAG > CTAG','obj',3,'p_obj','test.py',48),
  ('obj -> OTAG > CONTENT CTAG','obj',4,'p_obj','test.py',49),
  ('obj -> OTAG > obj CTAG','obj',4,'p_obj','test.py',50),
  ('obj -> OTAG CLASS > CTAG','obj',4,'p_obj','test.py',51),
  ('obj -> OTAG CLASS > CONTENT CTAG','obj',5,'p_obj','test.py',52),
  ('obj -> OTAG CLASS > obj CTAG','obj',5,'p_obj','test.py',53),
]
